#!/usr/bin/env python3
"""Report skill and eval coverage against the frozen IWE capability map."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts/iwe-v18.json"
CAPABILITIES = ROOT / "contracts/iwe-v18-capabilities.json"
SKILL = ROOT / "skills/iwe-v18/SKILL.md"
REFERENCES = ROOT / "skills/iwe-v18/references"
SCENARIOS = ROOT / "tests/eval/scenarios/iwe.eval.yaml"
REPORT = ROOT / "docs/iwe-v18-coverage-matrix.md"


def ratio(covered: int, total: int) -> dict[str, int | float]:
    return {
        "covered": covered,
        "total": total,
        "percent": round(100 * covered / total, 1) if total else 100.0,
    }


def load_report() -> tuple[dict, list[str]]:
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    catalog = json.loads(CAPABILITIES.read_text(encoding="utf-8"))
    skill = SKILL.read_text(encoding="utf-8")
    reference_text = "\n".join(
        path.read_text(encoding="utf-8") for path in sorted(REFERENCES.glob("*.md"))
    )
    scenarios = yaml.safe_load(SCENARIOS.read_text(encoding="utf-8"))["scenarios"]

    problems: list[str] = []
    commands = set(contract["commands"])
    capability_ids: set[str] = set()
    covered_ids: set[str] = set()
    core_ids: set[str] = set()
    for item in catalog["capabilities"]:
        capability_id = item["id"]
        if capability_id in capability_ids:
            problems.append(f"duplicate capability id: {capability_id}")
        capability_ids.add(capability_id)
        if item["command_family"] not in commands and item["command_family"] != "__global__":
            problems.append(f"unknown command family for {capability_id}: {item['command_family']}")
        marker = f"**{item['case']}"
        if item["tier"] == "core":
            core_ids.add(capability_id)
            if marker not in skill:
                problems.append(f"core capability is absent from SKILL.md: {capability_id} ({marker})")
            else:
                covered_ids.add(capability_id)
        elif marker in skill or marker in reference_text:
            covered_ids.add(capability_id)
        else:
            problems.append(f"extended capability is undocumented: {capability_id} ({marker})")

    command_covered = {
        name for name in commands
        if any(
            f"`{rendered}`" in text
            for rendered in (name, name.replace(".", " "))
            for text in (skill, reference_text)
        )
    }
    missing_commands = sorted(commands - command_covered)
    if missing_commands:
        problems.append("undocumented commands: " + ", ".join(missing_commands))

    eval_ids: set[str] = set()
    for scenario in scenarios:
        for capability_id in scenario["capabilities"]:
            if capability_id.startswith("behavior."):
                continue
            if capability_id not in capability_ids:
                problems.append(
                    f"scenario {scenario['id']} references unknown capability {capability_id}"
                )
            eval_ids.add(capability_id)

    core_covered = core_ids & covered_ids
    report = {
        "command_families": {
            **ratio(len(command_covered), len(commands)),
            "missing": missing_commands,
        },
        "capabilities": {
            **ratio(len(covered_ids), len(capability_ids)),
            "missing": sorted(capability_ids - covered_ids),
        },
        "core_capabilities": {
            **ratio(len(core_covered), len(core_ids)),
            "missing": sorted(core_ids - core_covered),
            "eval_covered": len(core_ids & eval_ids),
            "eval_percent": round(100 * len(core_ids & eval_ids) / len(core_ids), 1),
            "missing_eval": sorted(core_ids - eval_ids),
        },
        "scenario_count": len(scenarios),
    }
    return report, problems


def markdown(report: dict) -> str:
    command = report["command_families"]
    capability = report["capabilities"]
    core = report["core_capabilities"]
    missing_eval = "\n".join(f"- `{item}`" for item in core["missing_eval"]) or "- None"
    return f"""# IWE v0.18 skill and eval coverage

Generated by `python3 scripts/report_iwe_coverage.py --write` from the frozen CLI contract,
capability catalog, installed skill, linked references, and scenario metadata.

| Measure | Coverage |
| --- | ---: |
| Command families | {command['covered']}/{command['total']} ({command['percent']}%) |
| All capabilities | {capability['covered']}/{capability['total']} ({capability['percent']}%) |
| Core capabilities in `SKILL.md` | {core['covered']}/{core['total']} ({core['percent']}%) |
| Core capabilities with eval scenarios | {core['eval_covered']}/{core['total']} ({core['eval_percent']}%) |

## Core capabilities without eval coverage

{missing_eval}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    report, problems = load_report()
    rendered = markdown(report)
    if args.write:
        REPORT.write_text(rendered, encoding="utf-8")
    if args.check:
        if not REPORT.is_file() or REPORT.read_text(encoding="utf-8") != rendered:
            problems.append(f"stale generated report: {REPORT.relative_to(ROOT)}")
    if args.json:
        print(json.dumps(report, separators=(",", ":")))
    else:
        sys.stdout.write(rendered)
    if problems:
        for problem in problems:
            print(f"ERROR: {problem}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
